config/routes.rb
Rails.application.routes.draw do
  scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do
    post '/users', to: 'users#create'

    devise_for :users,
               controllers: {
                 confirmations: 'users/confirmations',
                 omniauth: 'users/omniauth',
                 passwords: 'users/passwords',
                 registrations: 'users/registrations',
                 sessions: 'users/sessions',
                 unlocks: 'users/unlocks'
               },
               path_names: {sign_in: 'login', sign_out: 'logout'},
               constraints: { format: :html }

    match '/admin', :to => 'admin#index', :as => :admin, :via => :get
    namespace :admin do
      resources :users, constraints: { format: :html }
      resources :page_contents, constraints: { format: :html }
    end

    get '/explore/:nameable_type/:nameable_id',
        to: 'root#temp_nameable_show',
        as: 'nameable'

    root 'root#index'
    get '/about' => 'root#about'
    get '/list' => 'root#list'
    get '/csv/complete_primary_finances' => 'csv#complete_primary_finances'

    scope module: :api do
      namespace :v1 do
        resources :page_contents, only: :show, constraints: { format: :json }
        get '/last_updated_date' => 'last_updated_date#index'

        get '/budget_items/:id' => 'budget_items#show'
        get '/programs' => 'budget_items#programs'
        get '/spending_agencies' => 'budget_items#spending_agencies'
        get '/priorities' => 'budget_items#priorities'
      end
    end

    # handles /en/fake/path/whatever
    get '*path', to: redirect("/#{I18n.default_locale}")
  end

  # handles /
  get '', to: redirect("/#{I18n.default_locale}")

  # handles /not-a-locale/anything
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
end

app/controllers/application_controller.rb
# The central controller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  ##############################################
  # Actions #

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
  private :set_locale

  ##############################################

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

  ##############################################
  # helpers

  def clean_filename(filename)
    filename.strip.to_slug.transliterate.to_s.gsub(' ', '_').gsub(/[\\ \/ \: \* \? \" \< \> \| \, \. ]/,'')
  end

  ##############################################
  # Authorization #

  # role is either the name of the role (string) or an array of role names (string)
  def valid_role?(role)
    redirect_to root_path(locale: I18n.locale), :notice => t('shared.msgs.not_authorized') if !current_user || !((role.is_a?(String) && current_user.is?(role)) || (role.is_a?(Array) && role.include?(current_user.role.name)))
  end

  rescue_from CanCan::AccessDenied do |_exception|
    if user_signed_in?
      not_authorized(root_path(locale: I18n.locale))
    else
      not_authorized
    end
  end

  def not_authorized(redirect_path = new_user_session_path)
    redirect_to redirect_path, alert: t('shared.msgs.not_authorized')
  rescue ActionController::RedirectBackError
    redirect_to root_path(locale: I18n.locale)
  end

  def not_found(redirect_path = root_path(locale: I18n.locale))
    redirect_to redirect_path,
                notice: t('shared.msgs.does_not_exist')
  end
end

app/helpers/application_helper.rb
# General helpers for application views
module ApplicationHelper
  def page_title(page_title)
    content_for(:page_title) { page_title.html_safe }
  end

  def current_url
    "#{request.protocol}#{request.host_with_port}#{request.fullpath}"
  end

  def full_url(path)
    "#{request.protocol}#{request.host_with_port}#{path}"
  end

  # apply the strip_tags helper and also convert nbsp to a ' '
  def strip_tags_nbsp(text)
    if text.present?
      strip_tags(text.gsub('&nbsp;', ' '))
    end
  end

  # from http://www.kensodev.com/2012/03/06/better-simple_format-for-rails-3-x-projects/
  # same as simple_format except it does not wrap all text in p tags
  def simple_format_no_tags(text, _html_options = {}, options = {})
    text = '' if text.nil?
    text = smart_truncate(text, options[:truncate]) if options[:truncate].present?
    text = sanitize(text) unless options[:sanitize] == false
    text = text.to_str
    text.gsub!(/\r\n?/, "\n")                    # \r\n and \r -> \n
    #   text.gsub!(/([^\n]\n)(?=[^\n])/, '\1<br />') # 1 newline   -> br
    text.html_safe
  end

  # sort the locales so the default locale is first and then the rest are alpha
  def sort_locales(locales)
    if locales.present?
      # sort
      locales.sort!

      # move default locale to first position
      default = locales.index{|x| x == I18n.default_locale}
      if default.present? && default > 0
        locales.unshift(locales[default])
        locales.delete_at(default+1)
      end
    end
    return locales
  end

end

app/views/application/_footer.html.erb
<footer class='app-footer'>
  <p class='app-footer-left'>&copy; <%= Time.now.year %></p>
  <%= link_to image_tag('jumpstart-logo.png', class: 'app-footer-right'),
              'http://jumpstart.ge',
              target: '_blank',
              title: t('shared.common.jumpstart.slogan') %>
</footer>

app/views/application/_google_analytics.html.erb
<script>
  if (typeof ga === 'undefined') {
    var property_id = 'UA-12801815-49';

    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', property_id, 'auto');
  }
</script>

app/views/application/_head.html.erb
<head>

  <%-
    title = (content_for?(:page_title) && yield(:page_title) != t('shared.common.name') ? "#{strip_tags_nbsp(yield(:page_title))} | #{t('shared.common.name')}" :
              t('shared.common.name')).html_safe
    desc = t("shared.common.description").html_safe
  -%>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= title %></title>

  <meta property="og:title" content="<%= title %>">
  <meta name="description" content="<%= desc %>">
  <meta property="og:description" content="<%= desc %>" />
  <meta property="og:type" content="non_profit" />
  <meta property="og:url" content="<%= current_url %>" />
  <!--meta property="og:image" content="<%= image_url("shareimage.png") %>" /-->
  <meta property="og:site_name" content="<%= t("shared.common.name") %>" />


  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= render partial: 'application/head/favicons' %>
  <%= javascript_include_tag "application" %>
</head>

app/views/application/_loading_indicator.html.erb
<div class='loading-indicator'>
  <%= image_tag('loading_apple.gif', class: 'loading-indicator-image') %>
</div>

app/views/application/_main.html.erb
<main>
  <div class="container">
    <%= bootstrap_flash %>

    <% if content_for? :page_title %>
      <h1 class='primary-header'><%= yield(:page_title) %></h1>
    <% end %>

    <%= yield %>
  </div>
</main>

app/views/application/_navbar_header.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to t('shared.common.name'), root_path, class: 'navbar-brand' %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to 'List', list_path %></li>
      </ul>
      <ul class='nav navbar-nav navbar-right'>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" id="user-dropdown" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <%= icon('user')%>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <% if current_user.is?(['super_admin', 'site_admin', 'content_manager']) %>
                <li><%= link_to t('shared.links.page_contents'), admin_page_contents_path %></li>
              <% end %>
              <% if current_user.is?(['super_admin', 'site_admin']) %>
                <li><%= link_to t('activerecord.models.user', count: 999), admin_users_path %></li>
              <% end %>
              <li class='divider'>

              </li>
              <li>
                <%= link_to t('.account.edit_profile'),
                            edit_user_registration_path %>
              </li>
              <li>
                <%= link_to t('.account.logout'),
                            destroy_user_session_path,
                            method: :delete %>
              </li>
            </ul>
          </li>
        <% end %>

        <li class='language-switcher-container'>
          <ul class='language-switcher'>
            <% I18n.available_locales.each do |locale| %>
              <li class='language-switcher-item <%= "is-active" if I18n.locale == locale %>'>
                <%=
                if I18n.locale == locale
                  link_to t("shared.locale.short.#{locale}"),
                          url_for(locale: locale),
                          class: 'language-switcher-item-link is-active'
                else
                  link_to t("shared.locale.short.#{locale}"),
                          url_for(locale: locale),
                          class: 'language-switcher-item-link'
                end %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>